/** Paleta alinhada com notifyorg (tailwind.config.js — Material 3). */
export const colors = {
  primary: "#0d3873",
  onPrimary: "#ffffff",
  primaryContainer: "#2c508c",
  onPrimaryContainer: "#a8c4ff",
  secondary: "#006494",
  onSecondary: "#ffffff",
  secondaryContainer: "#7cc5fd",
  onSecondaryContainer: "#00527a",
  background: "#f2f5f8",
  surface: "#faf9f9",
  surfaceContainer: "#efeded",
  surfaceContainerHigh: "#e9e8e8",
  onSurface: "#1b1c1c",
  onSurfaceVariant: "#434750",
  outline: "#747781",
  outlineVariant: "#c3c6d1",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  tertiary: "#163484",
  inverseSurface: "#2f3031",
} as const
