import forms from "@tailwindcss/forms"
import containerQuery from "@tailwindcss/container-queries"

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#d7e2ff",
        "inverse-surface": "#2f3031",
        "on-surface-variant": "#434750",
        "secondary-fixed-dim": "#8ecdff",
        "inverse-on-surface": "#f2f0f0",
        "primary-container": "#2c508c",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001a40",
        "on-primary-container": "#a8c4ff",
        "on-surface": "#1b1c1c",
        surface: "#faf9f9",
        "on-tertiary-container": "#b3c2ff",
        "on-tertiary-fixed": "#00164e",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e3e2e2",
        "tertiary-fixed": "#dce1ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#264191",
        "on-background": "#1b1c1c",
        "on-secondary-fixed-variant": "#004b71",
        "tertiary-container": "#324c9c",
        tertiary: "#163484",
        "outline-variant": "#c3c6d1",
        "surface-tint": "#3b5e9b",
        "surface-dim": "#dbdad9",
        "surface-variant": "#e3e2e2",
        outline: "#747781",
        error: "#ba1a1a",
        primary: "#0d3873",
        "on-error": "#ffffff",
        "inverse-primary": "#acc7ff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#efeded",
        "surface-bright": "#faf9f9",
        "on-secondary-container": "#00527a",
        "primary-fixed-dim": "#acc7ff",
        "on-primary-fixed-variant": "#204681",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e8",
        secondary: "#006494",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#cbe6ff",
        "tertiary-fixed-dim": "#b6c4ff",
        "secondary-container": "#7cc5fd",
        "on-secondary-fixed": "#001e30",
        background: "#faf9f9",
        "on-tertiary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        unit: "8px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg": ["Public Sans", "sans-serif"],
        "headline-xl": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms, containerQuery],
}
